version: '2'
services:
  server:
    build: ./server
    container_name: "weatherlab-server"
    ports:
      - "5000:5000"
    volumes:
      - "./server:/app"
  influx:
    image: "influxdb:alpine"
    container_name: "influx"
    ports:
      - "8086:8086"
